# Copyright 2021 Teak.io, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

setup: true

orbs:
  teak: teak/sdk-utils@0.9

parameters:
  region:
    type: string
    default: us-east-1
  # Work around CircleCI brain damage.
  # It is an error for a continuation to _not_ change a pipeline parameter. We drop the in_ prefix
  # from these parameters in continue.yml, so that Circle sees changes.
  in_build_account_slug:
    type: string
    default: ''
  in_deploy_account_slug:
    type: string
    default: ''

references:
  ONLY_STAGE: &ONLY_STAGE
    filters:
      branches:
        only:
          - stage
  ONLY_MAIN: &ONLY_MAIN
    filters:
      branches:
        only:
          - main

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - teak/packer-install:
          version: 1.7.5-dev2
          github_releases_user: AlexSc
          gpg_key_id: EC3A3F7C6C4F9D25

workflows:
  version: 2
  full:
    jobs:
      - teak/ami-update-continuation:
          <<: *ONLY_STAGE
          region: << pipeline.parameters.region >>
          deploy_account_slug: stage-workload
          build_account_slug: stage-ci-cd
      - teak/ami-update-continuation:
          <<: *ONLY_MAIN
          region: << pipeline.parameters.region >>
          deploy_account_slug: prod-workload
          build_account_slug: prod-ci-cd
