# Copyright 2021 Teak.io, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

orbs:
  teak: teak/sdk-utils@0.9

references:
  packer-build: &packer-build
    version: 1.7.5-dev2
    github_releases_user: AlexSc
    gpg_key_id: EC3A3F7C6C4F9D25
    name: "Generate Images (<< pipeline.parameters.build_account_slug >>); DO NOT CANCEL!"
    pre-steps:
      - run:
          command: sudo apt-get update && sudo apt-get install -y --no-install-recommends ansible awscli jq
      - run:
          command: |
            ip=$(curl -s https://api.ipify.org)
            echo "My public IP address is: $ip"
    post-steps:
      - store_artifacts:
          path: "manifests/"
      - store_artifacts:
          path: "raw_manifests/"
    path: "packer"
    except: "amazon-ebs.*" # Exclude Vagrant builds.
    var: "region=<< pipeline.parameters.region >>,build_account_canonical_slug=<< pipeline.parameters.build_account_slug >>,cost_center=root_image"
    context:
      - AWS-Write

parameters:
  region:
    type: string
    default: us-east-1
  build_account_slug:
    type: string
    default: ""
  deploy_account_slug:
    type: string
    default: ""
  # Work around CircleCI brain damage.
  # Continuation pipelines must declare all the same parameters as the setup pipeline, even
  # though it's an error to just reuse those parameters without changes.
  in_build_account_slug:
    type: string
    default: ''
  in_deploy_account_slug:
    type: string
    default: ''

workflows:
  version: 2
  build-only:
    jobs:
      - teak/packer-build:
          <<: *packer-build
      - teak/build-dependent-images:
          region: << pipeline.parameters.region >>
          build_account_slug: << pipeline.parameters.build_account_slug >>
          ami_name_prefix: "root"
          requires:
            - "Generate Images (<< pipeline.parameters.build_account_slug >>); DO NOT CANCEL!"
          context:
            - AWS
            - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
